version: "3"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    # restart: always

    environment:
      MYSQL_ROOT_PASSWORD: SECRET
      MYSQL_DATABASE: task
      MYSQL_USER: USER
      MYSQL_PASSWORD: SECRET
    networks:
      - backend

  backend:
    # image: nomanikram/task-backend
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      # - elasticsearch
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "80:8000"
    depends_on:
      - backend
      # - elasticsearch
    networks:
      - backend
      

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node

    networks:
      - backend

networks:
  backend: